### ISSUE TITLE
No BGP authcode in the default TF

### ISSUE THREAD

**Issue by larrymapacket** [equinix-labs/terraform-equinix-metal-vrf#10]
The current TF scripts doesn't have BGP authcode in:
resource "equinix_metal_virtual_circuit" "my_vc_pri"

Need to:
1. define the BGP autcode in variables.tf
2. define default BGP authcode in example.tfvars
3. Add BGP authcode (md5) in resource "equinix_metal_virtual_circuit" "my_vc_pri" and resource "equinix_metal_virtual_circuit" "my_vc_sec" by following the document here - https://registry.terraform.io/providers/equinix/equinix/latest/docs/resources/equinix_metal_virtual_circuit
4. Change README file to mention the BGP authcode (md5)

**Comment by Paulius0112** [comment]
Added BGP md5 support for both virtual circuits. https://github.com/equinix-labs/terraform-equinix-metal-vrf/pull/11
