### ISSUE TITLE
422 param is missing or the value is empty

### ISSUE THREAD

**Issue by Paulius0112** [equinix-labs/terraform-equinix-metal-vrf#7]
Trying to follow the tutorial, I face a problem creating equinix_metal_virtual_circuit.my_vc_pri resource. Getting this error 
`│ Error: POST https://api.equinix.com/metal/v1/projects/<project-id>connections/(connection-id)/ports/<port-id>/virtual-circuits: 422 param is missing or the value is empty: vnid
│
│   with equinix_metal_virtual_circuit.my_vc_pri,
│   on main.tf line 97, in resource "equinix_metal_virtual_circuit" "my_vc_pri":
│   97: resource "equinix_metal_virtual_circuit" "my_vc_pri" {
│`

Any idea why?

**Comment by larrymapacket** [comment]
Hi ! Do you have a dedicated port in your organization?

**Comment by Paulius0112** [comment]
It's not a dedicated port. We are using Fabric VC.

Is it only supported for Dedicated Port?

**Comment by larrymapacket** [comment]
Correct, VRF is currently only supported on dedicated ports. shared ports is to be supported ~Q1 2023.
I'll make it clear in the README part (#7)

**Comment by displague** [comment]
Noting that there is some context in the Equinix Metal community Slack around this:
https://eqix-metal-community.slack.com/archives/C4FEV702E/p1667485552591249

**Comment by Paulius0112** [comment]
Closing the issue, as it was resolved. Thanks
